---
# TASK DESCRIPTION:
# Always runs fist.  Confirms we can actually use Ansible
- name: sanity - user mode
  become: false
  ansible.builtin.debug:
    msg: "sanity check: user mode"

- name: sanity - become mode
  become: true
  ansible.builtin.debug:
    msg: "sanity check: become mode"
